### ISSUE TITLE
Error: AttributeError: module 'keylogger' has no attribute 'Keylogger'

### ISSUE THREAD

**Issue by oscarmoraog** [PushpenderIndia/Sinister#75]
Hey, Everything runs well, but when trying to run the resultant file I'm getting this issue, any hint? 

Traceback (most recent call last):
  File "trw_true.py", line 1, in <module>
  File "<string>", line 14, in <module>
  File "<string>", line 9, in check_and_start
AttributeError: module 'keylogger' has no attribute 'Keylogger'

**Comment by oscarmoraog** [comment]
Nevermind, it's related to windows defender, it's removing the files from the Sinister folder once it's recognized.
